FROM caddy:2.11.3-builder AS builder

RUN xcaddy build --with github.com/caddy-dns/porkbun

FROM caddy:2.11.3

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

WORKDIR /caddy

COPY Caddyfile ./

CMD ["caddy", "run"]
